### ISSUE TITLE
Cookbook fails with chef-solo

### ISSUE THREAD

**Issue by kmf** [chef-partners/chef-hipchat-plugin-cookbook#3]
Any ideas?

`
================================================================================
    Error executing action run on resource 'execute[install the dependent node modules]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received ''
    ---- Begin output of npm install ----
    STDOUT: > ursa@0.9.1 install /srv/chef-hipchat-plugin/node_modules/chef-api/node_modules/ursa
    > node-gyp rebuild
    
    make: Entering directory `/srv/chef-hipchat-plugin/node_modules/chef-api/node_modules/ursa/build'
      CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
    STDERR: npm WARN engine request@2.81.0: wanted: {"node":">= 4"} (current: {"node":"0.10.48","npm":"2.15.1"})
    npm WARN engine rsvp@3.5.0: wanted: {"node":"0.12.* || 4.* || 6.* || 7.*"} (current: {"node":"0.10.48","npm":"2.15.1"})
    npm WARN excluding symbolic link test/symlinks/dir1/dangling-symlink -> does-not-exist
    npm WARN engine form-data@2.1.4: wanted: {"node":">= 0.12"} (current: {"node":"0.10.48","npm":"2.15.1"})
    npm WARN engine har-validator@4.2.1: wanted: {"node":">=4"} (current: {"node":"0.10.48","npm":"2.15.1"})
    npm WARN engine har-schema@1.0.5: wanted: {"node":">=4"} (current: {"node":"0.10.48","npm":"2.15.1"})
    npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
    npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
    ---- End output of npm install ----
    Ran npm install returned 
    
    Resource Declaration:
    ---------------------
    # In /home/obstech/cookbooks/chef-hipchat-plugin/recipes/default.rb
    
     48: execute "install the dependent node modules" do
     49:   cwd "/srv/chef-hipchat-plugin"
     50:   command "npm install"
     51:   creates "/srv/chef-hipchat-plugin/node_modules/chef-api"
     52:   action :run
     53: end
     54: 
    
    Compiled Resource:
    ------------------
    # Declared in /home/obstech/cookbooks/chef-hipchat-plugin/recipes/default.rb:48:in `from_file'
    
    execute("install the dependent node modules") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :execute
      command "npm install"
      backup 5
      creates "/srv/chef-hipchat-plugin/node_modules/chef-api"
      cwd "/srv/chef-hipchat-plugin"
      returns 0
      user nil
      declared_type :execute
      cookbook_name "chef-hipchat-plugin"
      recipe_name "default"
    end
    
    Platform:
    ---------
    x86_64-linux
```
[2017-05-16T08:28:58+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2017-05-16T08:28:58+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-05-16T08:28:58+00:00] ERROR: Exception handlers complete
Chef Client failed. 6 resources updated in 02 minutes 03 seconds
[2017-05-16T08:28:58+00:00] FATAL: Stacktrace dumped to /home/obstech/chef-stacktrace.out
[2017-05-16T08:28:58+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-05-16T08:28:58+00:00] ERROR: execute[install the dependent node modules] (chef-hipchat-plugin::default line 48) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received ''
---- Begin output of npm install ----
STDOUT: > ursa@0.9.1 install /srv/chef-hipchat-plugin/node_modules/chef-api/node_modules/ursa
> node-gyp rebuild

make: Entering directory `/srv/chef-hipchat-plugin/node_modules/chef-api/node_modules/ursa/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
STDERR: npm WARN engine request@2.81.0: wanted: {"node":">= 4"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine rsvp@3.5.0: wanted: {"node":"0.12.* || 4.* || 6.* || 7.*"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN excluding symbolic link test/symlinks/dir1/dangling-symlink -> does-not-exist
npm WARN engine form-data@2.1.4: wanted: {"node":">= 0.12"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine har-validator@4.2.1: wanted: {"node":">=4"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine har-schema@1.0.5: wanted: {"node":">=4"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
---- End output of npm install ----
Ran npm install returned 
[2017-05-16T08:28:58+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
`
```

**Comment by jjasghar** [comment]
Ah, it seems that updates or dependency issues. I guess I'll have to revisit this to see what's changed.

**Comment by iennae** [comment]
Can you provide additional details such as Chef-client version and
Platform Details? I just did a test converge with the kitchen configuration with Ubuntu 14.04 and it successfully converges.

**Comment by kmf** [comment]
Chef-client = 12.20.3
Ubuntu 14.04.5 LTS

**Comment by kmf** [comment]
did kitchen tests worked great, provisioned via a chef-server worked as well

**Comment by iennae** [comment]
Thanks for letting us know.
